import type { DeployConfig } from '../types.js';

/**
 * Generates a Dockerfile for running the standalone agent server.
 *
 * Uses node:20-alpine for a minimal image. The generated server.mjs is
 * copied in and run directly -- no npm install needed since it has zero
 * external dependencies.
 */
export function generateDockerfile(): string {
  return `# Auto-generated by QAYANI CLI
FROM node:20-alpine

WORKDIR /app

# Copy the self-contained server
COPY server.mjs .

# The server reads PORT from the environment (default 3000)
EXPOSE 3000

CMD ["node", "server.mjs"]
`;
}

/**
 * Generates a docker-compose.yml for the agent server.
 *
 * Maps the configured port, passes through environment variables, and sets
 * restart: unless-stopped for resilience.
 */
export function generateDockerCompose(config: DeployConfig): string {
  const port = config.port ?? 3000;
  const serviceName = config.name.toLowerCase().replace(/[^a-z0-9_-]/g, '-');

  // Build the environment block
  const envLines: string[] = [];
  envLines.push(`      PORT: "${port}"`);

  if (config.env) {
    for (const [key, value] of Object.entries(config.env)) {
      // Use ${VAR} syntax so docker-compose reads from the host environment
      envLines.push(`      ${key}: "\${${key}:-${value}}"`);
    }
  } else {
    // Default: pass through the common API key env vars
    envLines.push(`      OPENAI_API_KEY: "\${OPENAI_API_KEY:-}"`);
    envLines.push(`      ANTHROPIC_API_KEY: "\${ANTHROPIC_API_KEY:-}"`);
    envLines.push(`      GOOGLE_API_KEY: "\${GOOGLE_API_KEY:-}"`);
    envLines.push(`      LLM_BASE_URL: "\${LLM_BASE_URL:-}"`);
  }

  return `# Auto-generated by QAYANI CLI
version: "3.8"

services:
  ${serviceName}:
    build: .
    ports:
      - "${port}:${port}"
    environment:
${envLines.join('\n')}
    restart: unless-stopped
`;
}
