import type { AgentConfig } from '../../agent/types.js';

/**
 * Generates a self-contained Node.js server (server.mjs) that wraps an agent.
 *
 * The generated file uses only built-in Node.js modules (http, fs, path) and
 * the global fetch() API (available in Node 18+). It embeds the system prompt
 * and agent configuration directly, so it can be run with `node server.mjs`.
 */
export function generateStandaloneServer(
  agentConfig: AgentConfig,
  systemPrompt: string,
): string {
  const configJson = JSON.stringify(
    {
      name: agentConfig.name,
      version: agentConfig.version,
      description: agentConfig.description,
      model: agentConfig.model,
    },
    null,
    2,
  );

  // Escape backticks and ${} in the system prompt so it can live inside a template literal
  const escapedPrompt = systemPrompt
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

  return `#!/usr/bin/env node
// ─────────────────────────────────────────────────────────────────────────────
// Auto-generated by QAYANI CLI — standalone agent server
// Run with: node server.mjs
// ─────────────────────────────────────────────────────────────────────────────

import { createServer } from 'node:http';

// ── Embedded configuration ───────────────────────────────────────────────────

const AGENT_CONFIG = ${configJson};

const SYSTEM_PROMPT = \`${escapedPrompt}\`;

const PORT = parseInt(process.env.PORT ?? '${agentConfig.model?.name ? '3000' : '3000'}', 10);

// ── Provider API mapping ─────────────────────────────────────────────────────

const PROVIDER_ENDPOINTS = {
  openai: 'https://api.openai.com/v1/chat/completions',
  anthropic: 'https://api.openai.com/v1/chat/completions', // fallback to OpenAI-compatible
  google: 'https://api.openai.com/v1/chat/completions',    // fallback to OpenAI-compatible
};

const API_KEY_ENV = {
  openai: 'OPENAI_API_KEY',
  anthropic: 'ANTHROPIC_API_KEY',
  google: 'GOOGLE_API_KEY',
};

function getApiKey() {
  const envVar = API_KEY_ENV[AGENT_CONFIG.model.provider] ?? 'OPENAI_API_KEY';
  const key = process.env[envVar];
  if (!key) {
    console.error(\`Missing API key. Set the \${envVar} environment variable.\`);
    process.exit(1);
  }
  return key;
}

function getEndpoint() {
  // Allow overriding with a custom base URL (useful for OpenAI-compatible providers)
  if (process.env.LLM_BASE_URL) {
    return process.env.LLM_BASE_URL.replace(/\\/$/, '') + '/chat/completions';
  }
  return PROVIDER_ENDPOINTS[AGENT_CONFIG.model.provider] ?? PROVIDER_ENDPOINTS.openai;
}

// ── CORS headers ─────────────────────────────────────────────────────────────

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

// ── Helpers ──────────────────────────────────────────────────────────────────

function jsonResponse(res, status, body) {
  const payload = JSON.stringify(body);
  res.writeHead(status, {
    ...CORS_HEADERS,
    'Content-Type': 'application/json',
    'Content-Length': Buffer.byteLength(payload),
  });
  res.end(payload);
}

function parseBody(req) {
  return new Promise((resolve, reject) => {
    const chunks = [];
    req.on('data', (chunk) => chunks.push(chunk));
    req.on('end', () => {
      try {
        const raw = Buffer.concat(chunks).toString('utf-8');
        resolve(raw ? JSON.parse(raw) : {});
      } catch (err) {
        reject(new Error('Invalid JSON in request body'));
      }
    });
    req.on('error', reject);
  });
}

// ── LLM call (non-streaming) ─────────────────────────────────────────────────

async function callLLM(userMessage) {
  const apiKey = getApiKey();
  const endpoint = getEndpoint();

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': \`Bearer \${apiKey}\`,
    },
    body: JSON.stringify({
      model: AGENT_CONFIG.model.name,
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userMessage },
      ],
      temperature: AGENT_CONFIG.model.temperature ?? 0.7,
      max_tokens: AGENT_CONFIG.model.maxTokens ?? 2048,
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(\`LLM API error (\${response.status}): \${errText}\`);
  }

  const data = await response.json();
  return data.choices?.[0]?.message?.content ?? '';
}

// ── LLM call (streaming) ─────────────────────────────────────────────────────

async function callLLMStream(userMessage, res) {
  const apiKey = getApiKey();
  const endpoint = getEndpoint();

  const response = await fetch(endpoint, {
    method: 'POST',
    headers: {
      'Content-Type': 'application/json',
      'Authorization': \`Bearer \${apiKey}\`,
    },
    body: JSON.stringify({
      model: AGENT_CONFIG.model.name,
      messages: [
        { role: 'system', content: SYSTEM_PROMPT },
        { role: 'user', content: userMessage },
      ],
      temperature: AGENT_CONFIG.model.temperature ?? 0.7,
      max_tokens: AGENT_CONFIG.model.maxTokens ?? 2048,
      stream: true,
    }),
  });

  if (!response.ok) {
    const errText = await response.text();
    throw new Error(\`LLM API error (\${response.status}): \${errText}\`);
  }

  res.writeHead(200, {
    ...CORS_HEADERS,
    'Content-Type': 'text/event-stream',
    'Cache-Control': 'no-cache',
    'Connection': 'keep-alive',
  });

  const reader = response.body.getReader();
  const decoder = new TextDecoder();
  let buffer = '';

  try {
    while (true) {
      const { done, value } = await reader.read();
      if (done) break;

      buffer += decoder.decode(value, { stream: true });
      const lines = buffer.split('\\n');
      buffer = lines.pop() ?? '';

      for (const line of lines) {
        const trimmed = line.trim();
        if (!trimmed || !trimmed.startsWith('data: ')) continue;

        const payload = trimmed.slice(6);
        if (payload === '[DONE]') {
          res.write('data: [DONE]\\n\\n');
          continue;
        }

        try {
          const parsed = JSON.parse(payload);
          const content = parsed.choices?.[0]?.delta?.content;
          if (content) {
            res.write(\`data: \${JSON.stringify({ content })}\\n\\n\`);
          }
        } catch {
          // Skip malformed SSE chunks
        }
      }
    }
  } finally {
    res.end();
  }
}

// ── Route handler ────────────────────────────────────────────────────────────

async function handleRequest(req, res) {
  const url = new URL(req.url, \`http://\${req.headers.host}\`);
  const method = req.method?.toUpperCase();

  // Handle CORS preflight
  if (method === 'OPTIONS') {
    res.writeHead(204, CORS_HEADERS);
    res.end();
    return;
  }

  // POST /chat — non-streaming chat
  if (method === 'POST' && url.pathname === '/chat') {
    try {
      const body = await parseBody(req);
      if (!body.message || typeof body.message !== 'string') {
        return jsonResponse(res, 400, { error: 'Missing "message" field (string)' });
      }
      const response = await callLLM(body.message);
      return jsonResponse(res, 200, { response });
    } catch (err) {
      return jsonResponse(res, 500, { error: err.message ?? 'Internal server error' });
    }
  }

  // POST /chat/stream — SSE streaming chat
  if (method === 'POST' && url.pathname === '/chat/stream') {
    try {
      const body = await parseBody(req);
      if (!body.message || typeof body.message !== 'string') {
        return jsonResponse(res, 400, { error: 'Missing "message" field (string)' });
      }
      await callLLMStream(body.message, res);
      return;
    } catch (err) {
      // If headers already sent, just close the connection
      if (res.headersSent) {
        res.end();
        return;
      }
      return jsonResponse(res, 500, { error: err.message ?? 'Internal server error' });
    }
  }

  // GET /health — health check
  if (method === 'GET' && url.pathname === '/health') {
    return jsonResponse(res, 200, { status: 'ok', agent: AGENT_CONFIG.name });
  }

  // GET /info — agent info
  if (method === 'GET' && url.pathname === '/info') {
    return jsonResponse(res, 200, {
      name: AGENT_CONFIG.name,
      version: AGENT_CONFIG.version,
      description: AGENT_CONFIG.description,
      model: {
        provider: AGENT_CONFIG.model.provider,
        name: AGENT_CONFIG.model.name,
      },
    });
  }

  // 404 for everything else
  return jsonResponse(res, 404, { error: 'Not found' });
}

// ── Start server ─────────────────────────────────────────────────────────────

const server = createServer(handleRequest);

server.listen(PORT, () => {
  console.log('');
  console.log(\`  QAYANI Agent Server\`);
  console.log(\`  Agent:    \${AGENT_CONFIG.name} v\${AGENT_CONFIG.version}\`);
  console.log(\`  Model:    \${AGENT_CONFIG.model.provider} / \${AGENT_CONFIG.model.name}\`);
  console.log(\`  Listening: http://localhost:\${PORT}\`);
  console.log('');
  console.log(\`  Endpoints:\`);
  console.log(\`    POST /chat          Send a message (JSON: { message: string })\`);
  console.log(\`    POST /chat/stream   Send a message (SSE streaming)\`);
  console.log(\`    GET  /health        Health check\`);
  console.log(\`    GET  /info          Agent info\`);
  console.log('');
});
`;
}
