import type { AgentConfig } from '../../agent/types.js';

/**
 * Generates a complete Vercel-compatible project for deploying an agent
 * as a serverless function.
 *
 * Returns a Map of filePath -> fileContent. The caller writes these to disk.
 */
export function generateVercelProject(
  agentConfig: AgentConfig,
  systemPrompt: string,
): Map<string, string> {
  const files = new Map<string, string>();

  files.set('api/chat.js', generateChatHandler(agentConfig, systemPrompt));
  files.set('vercel.json', generateVercelConfig());
  files.set('package.json', generatePackageJson(agentConfig));

  return files;
}

// ── api/chat.js ──────────────────────────────────────────────────────────────

function generateChatHandler(
  agentConfig: AgentConfig,
  systemPrompt: string,
): string {
  const configJson = JSON.stringify(
    {
      name: agentConfig.name,
      version: agentConfig.version,
      description: agentConfig.description,
      model: agentConfig.model,
    },
    null,
    2,
  );

  const escapedPrompt = systemPrompt
    .replace(/\\/g, '\\\\')
    .replace(/`/g, '\\`')
    .replace(/\$\{/g, '\\${');

  return `// Auto-generated by QAYANI CLI — Vercel serverless function

const AGENT_CONFIG = ${configJson};

const SYSTEM_PROMPT = \`${escapedPrompt}\`;

const PROVIDER_ENDPOINTS = {
  openai: 'https://api.openai.com/v1/chat/completions',
  anthropic: 'https://api.openai.com/v1/chat/completions',
  google: 'https://api.openai.com/v1/chat/completions',
};

const API_KEY_ENV = {
  openai: 'OPENAI_API_KEY',
  anthropic: 'ANTHROPIC_API_KEY',
  google: 'GOOGLE_API_KEY',
};

function getApiKey() {
  const envVar = API_KEY_ENV[AGENT_CONFIG.model.provider] ?? 'OPENAI_API_KEY';
  const key = process.env[envVar];
  if (!key) {
    throw new Error(\`Missing API key: set \${envVar} in Vercel environment variables\`);
  }
  return key;
}

function getEndpoint() {
  if (process.env.LLM_BASE_URL) {
    return process.env.LLM_BASE_URL.replace(/\\/$/, '') + '/chat/completions';
  }
  return PROVIDER_ENDPOINTS[AGENT_CONFIG.model.provider] ?? PROVIDER_ENDPOINTS.openai;
}

const CORS_HEADERS = {
  'Access-Control-Allow-Origin': '*',
  'Access-Control-Allow-Methods': 'GET, POST, OPTIONS',
  'Access-Control-Allow-Headers': 'Content-Type, Authorization',
};

export default async function handler(req, res) {
  // CORS preflight
  if (req.method === 'OPTIONS') {
    res.writeHead(204, CORS_HEADERS);
    res.end();
    return;
  }

  // Set CORS headers on all responses
  for (const [key, value] of Object.entries(CORS_HEADERS)) {
    res.setHeader(key, value);
  }

  // GET /api/chat — return agent info (health check)
  if (req.method === 'GET') {
    return res.status(200).json({
      name: AGENT_CONFIG.name,
      version: AGENT_CONFIG.version,
      description: AGENT_CONFIG.description,
      model: {
        provider: AGENT_CONFIG.model.provider,
        name: AGENT_CONFIG.model.name,
      },
      status: 'ok',
    });
  }

  // POST /api/chat — send a message
  if (req.method === 'POST') {
    try {
      const { message, stream } = req.body ?? {};

      if (!message || typeof message !== 'string') {
        return res.status(400).json({ error: 'Missing "message" field (string)' });
      }

      const apiKey = getApiKey();
      const endpoint = getEndpoint();

      // ── Streaming response ───────────────────────────────────────────
      if (stream) {
        const response = await fetch(endpoint, {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
            'Authorization': \`Bearer \${apiKey}\`,
          },
          body: JSON.stringify({
            model: AGENT_CONFIG.model.name,
            messages: [
              { role: 'system', content: SYSTEM_PROMPT },
              { role: 'user', content: message },
            ],
            temperature: AGENT_CONFIG.model.temperature ?? 0.7,
            max_tokens: AGENT_CONFIG.model.maxTokens ?? 2048,
            stream: true,
          }),
        });

        if (!response.ok) {
          const errText = await response.text();
          return res.status(502).json({ error: \`LLM API error (\${response.status}): \${errText}\` });
        }

        res.setHeader('Content-Type', 'text/event-stream');
        res.setHeader('Cache-Control', 'no-cache');
        res.setHeader('Connection', 'keep-alive');

        const reader = response.body.getReader();
        const decoder = new TextDecoder();
        let buffer = '';

        try {
          while (true) {
            const { done, value } = await reader.read();
            if (done) break;

            buffer += decoder.decode(value, { stream: true });
            const lines = buffer.split('\\n');
            buffer = lines.pop() ?? '';

            for (const line of lines) {
              const trimmed = line.trim();
              if (!trimmed || !trimmed.startsWith('data: ')) continue;

              const payload = trimmed.slice(6);
              if (payload === '[DONE]') {
                res.write('data: [DONE]\\n\\n');
                continue;
              }

              try {
                const parsed = JSON.parse(payload);
                const content = parsed.choices?.[0]?.delta?.content;
                if (content) {
                  res.write(\`data: \${JSON.stringify({ content })}\\n\\n\`);
                }
              } catch {
                // Skip malformed SSE chunks
              }
            }
          }
        } finally {
          res.end();
        }
        return;
      }

      // ── Non-streaming response ───────────────────────────────────────
      const response = await fetch(endpoint, {
        method: 'POST',
        headers: {
          'Content-Type': 'application/json',
          'Authorization': \`Bearer \${apiKey}\`,
        },
        body: JSON.stringify({
          model: AGENT_CONFIG.model.name,
          messages: [
            { role: 'system', content: SYSTEM_PROMPT },
            { role: 'user', content: message },
          ],
          temperature: AGENT_CONFIG.model.temperature ?? 0.7,
          max_tokens: AGENT_CONFIG.model.maxTokens ?? 2048,
        }),
      });

      if (!response.ok) {
        const errText = await response.text();
        return res.status(502).json({ error: \`LLM API error (\${response.status}): \${errText}\` });
      }

      const data = await response.json();
      const content = data.choices?.[0]?.message?.content ?? '';

      return res.status(200).json({ response: content });
    } catch (err) {
      return res.status(500).json({ error: err.message ?? 'Internal server error' });
    }
  }

  // Unsupported method
  return res.status(405).json({ error: 'Method not allowed' });
}
`;
}

// ── vercel.json ──────────────────────────────────────────────────────────────

function generateVercelConfig(): string {
  const config = {
    version: 2,
    rewrites: [
      { source: '/chat', destination: '/api/chat' },
      { source: '/chat/stream', destination: '/api/chat' },
      { source: '/health', destination: '/api/chat' },
      { source: '/info', destination: '/api/chat' },
    ],
  };
  return JSON.stringify(config, null, 2) + '\n';
}

// ── package.json ─────────────────────────────────────────────────────────────

function generatePackageJson(agentConfig: AgentConfig): string {
  const pkg = {
    name: `${agentConfig.name}-agent`,
    version: agentConfig.version ?? '1.0.0',
    private: true,
    description: `QAYANI agent: ${agentConfig.description}`,
  };
  return JSON.stringify(pkg, null, 2) + '\n';
}
